[package]
name = "engiffen"
version = "0.1.0"
authors = ["Jesse Bees <jesse@toomanybees.com>"]

[dependencies]
image = "*"
gif = "*"
lab = "0.3"

[lib]
name = "engiffen"
path = "src/lib.rs"

[[bin]]
name = "engiffen_demo"
path = "src/main.rs"
